### ISSUE TITLE
Player shoot on right stick

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#53] opened 2018-06-05 12:46 UTC
Player should shoot with the right control stick, clipped to one of the eight directions (up, down, right, left and the diagonales). Currently, it is 360° and the right stick in addition with RB/R1 Button.
We need a way to enable/disable individual directions for testing.

~~It only shoots when the right trigger is pressed and the right stick is moved additionally. 
Please make it so that the laser is fired when only the right trigger is pressed in an according direction.~~

~~Also the button should be rt 2 and not rt 1 like it is now~~

~~the shoot stops at the invisible checkpoints~~

**Comment by truepaddii** [comment] 2018-06-06 09:52
There is a command pattern for bug reports in the industry.
It works like this:

*Steps to reproduce
1) first step
2) second step
3) third step
...

Expected result
- explain what you expected to happen in detail

Actual result
- explain what heppened instead in detail*

Please start using it because it makes it easier for us coders to test the bug and in case it's lacking info we can better track it or close the report as invalid. Future bug reports that do not have this pattern will be marked as invalid.

**Closed** 2018-06-21 09:15 UTC
Labels: feature
