### ISSUE TITLE
the game has to be started from the main menue

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#52] opened 2018-06-05 12:38 UTC
otherwise it is buggy. this makes it harder to playtest

**Comment by truepaddii** [comment] 2018-06-06 09:53
Future bug reports that have the wrong formatting will be marked as invalid. #53

**Comment by truepaddii** [comment] 2018-06-06 09:55
This is not a bug. This behaviour is intended.

**Closed** 2018-06-06 09:56 UTC
Labels: bug, wontfix
