### ISSUE TITLE
health of boss

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#40] opened 2018-05-22 14:55 UTC
boss can take damage from player attack 
- [ ] boss can get hurt by player laser
- [ ] boss can not get hurt by his own laser
- [ ] boss dies if hp reaches 0

**Comment by truepaddii** [comment] 2018-05-23 09:40
This issue is a duplicate of #39 since it's the same internally.

**Closed** 2018-05-23 09:40 UTC
Labels: duplicate, feature
